version: '3'

networks:
  default:
    external: false
  kabacorp:
    external: true

services:
  codechat:
    image: codechat/api:latest
    restart: always

    networks:
      kabacorp:
        ipv4_address: 172.19.0.103
    tty: true
    env_file: .env
    volumes:
      - ./instances:/home/api/instances
    command: [node, './dist/src/main.js']
#    ports:
#      - "8080:8083"