version: '3'

networks:
  default:
    external: false
  kabacorp:
    external: true

services:
   conector:
    image: edkaba/conector-conector 
    env_file: .env 
    restart: always
    networks:
      kabacorp:
        ipv4_address: 172.19.0.102
    tty: true
 #   ports:
 #     - "1234:1234"
