version: '3.8'

networks:
  default:
    external: false
  kabacorp:
    external: true

services:
  mongodb:
#    container_name: mongodb
    # This image already has a single replica set
    image: mongo
    restart: always
    volumes:
      # sudo mkdir -p /data/mongodb
      - ./data/mongodb:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      # Set a password to access the bank
      MONGO_INITDB_ROOT_PASSWORD: kabacorp
    networks:
      kabacorp:
        ipv4_address: 172.19.0.101
    tty: true